apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: entangled
data:
  mosquitto.conf: |
    port 1883
    allow_anonymous false
    password_file /mosquitto/config/password
